#Exam attempts and certificates
#Wed Apr 15 16:51:10 WAT 2026
attempts.aa@gmail.com.172=1
attempts.aa@gmail.com.173=2
attempts.aa@gmail.com.180=1
certificate.aa@gmail.com.172=C\:\\Users\\ABDOU\\desktop_educompus\\var\\certificates\\certificate_aa@gmail.com_172.pdf
certificate.aa@gmail.com.173=C\:\\Users\\ABDOU\\desktop_educompus\\var\\certificates\\certificate_aa@gmail.com_173.pdf
certificate.aa@gmail.com.180=C\:\\Users\\ABDOU\\desktop_educompus\\var\\certificates\\certificate_aa@gmail.com_180.pdf
passed.aa@gmail.com.172=true
passed.aa@gmail.com.173=true
passed.aa@gmail.com.180=true
