#Exam attempts and certificates
#Sun Apr 12 15:09:20 WAT 2026
passed.aa@gmail.com.40=true
passed.aa@gmail.com.33=true
passed.aa@gmail.com.43=true
attempts.aa@gmail.com.33=2
certificate.aa@gmail.com.33=D\:\\Gestion projets\\eduCompus-javafx\\var\\certificates\\certificate_aa@gmail.com_33.pdf
attempts.aa@gmail.com.43=1
certificate.aa@gmail.com.43=C\:\\Users\\senda\\OneDrive\\Bureau\\projet-javafx\\desktop_educompus\\var\\certificates\\certificate_aa@gmail.com_43.pdf
attempts.aa@gmail.com.40=1
certificate.aa@gmail.com.40=C\:\\Users\\senda\\OneDrive\\Bureau\\projet-javafx\\desktop_educompus\\var\\certificates\\certificate_aa@gmail.com_40.pdf
