#Exam attempts and certificates
#Mon Apr 13 23:43:22 WAT 2026
passed.aa@gmail.com.33=true
attempts.aa@gmail.com.36=2
certificate.aa@gmail.com.38=C\:\\Users\\ABDOU\\desktop_educompus\\var\\certificates\\certificate_aa@gmail.com_38.pdf
certificate.aa@gmail.com.35=C\:\\Users\\ABDOU\\desktop_educompus\\var\\certificates\\certificate_aa@gmail.com_35.pdf
passed.aa@gmail.com.42=true
attempts.aa@gmail.com.38=1
certificate.aa@gmail.com.36=C\:\\Users\\ABDOU\\desktop_educompus\\var\\certificates\\certificate_aa@gmail.com_36.pdf
attempts.aa@gmail.com.33=1
certificate.aa@gmail.com.33=C\:\\Users\\ABDOU\\desktop_educompus\\var\\certificates\\certificate_aa@gmail.com_33.pdf
attempts.aa@gmail.com.35=1
certificate.aa@gmail.com.42=C\:\\Users\\senda\\OneDrive\\Bureau\\projet-javafx\\desktop_educompus\\var\\certificates\\certificate_aa@gmail.com_42.pdf
attempts.aa@gmail.com.42=1
passed.aa@gmail.com.36=true
passed.aa@gmail.com.35=true
passed.aa@gmail.com.38=true
