#User placement results
#Tue May 05 16:29:43 WAT 2026
placement.en.aa@gmail.com=100
placement.en.dhirar@gmail.com=10
placement.en.gg@gmail.com=30
placement.en.s@gmail.com=70
placement.en.yy@gmail.com=90
placement.fr.aa@gmail.com=90
placement.fr.aminabalti@esprit.tn=90
placement.fr.dhirar@gmail.com=30
placement.fr.gg@gmail.com=10
placement.fr.s@gmail.com=80
placement.fr.student@gmail.com=20
placement.fr.yy@gmail.com=90
placement_done.aa@gmail.com=true
placement_done.aminabalti@esprit.tn=true
placement_done.dhirar@gmail.com=true
placement_done.gg@gmail.com=true
placement_done.s@gmail.com=true
placement_done.student@gmail.com=true
placement_done.yy@gmail.com=true
