#User placement results
#Sat May 02 15:30:01 WAT 2026
placement.en.aa@gmail.com=100
placement.en.aminabalti@esprit.tn=70
placement.en.yy@gmail.com=90
placement.fr.aa@gmail.com=90
placement.fr.aminabalti@esprit.tn=90
placement.fr.yy@gmail.com=90
placement_done.aa@gmail.com=true
placement_done.aminabalti@esprit.tn=true
placement_done.yy@gmail.com=true
