#User placement results
#Sat May 02 22:28:27 CET 2026
placement.en.student@gmail.com=80
placement_done.aa@gmail.com=true
placement.fr.aa@gmail.com=90
placement.en.aa@gmail.com=100
placement_done.student@gmail.com=true
placement.fr.student@gmail.com=20
placement_done.yy@gmail.com=true
placement.en.yy@gmail.com=90
placement.fr.yy@gmail.com=90
